/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgreementModule,
  IAgreementModuleInterface,
} from "../../../../contracts/src/interfaces/IAgreementModule";

const _abi = [
  {
    inputs: [],
    name: "moduleType",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
    ],
    name: "onActivate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "reason",
        type: "uint8",
      },
    ],
    name: "onTerminate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAgreementModule__factory {
  static readonly abi = _abi;
  static createInterface(): IAgreementModuleInterface {
    return new Interface(_abi) as IAgreementModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgreementModule {
    return new Contract(address, _abi, runner) as unknown as IAgreementModule;
  }
}
