/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IConditionResolver,
  IConditionResolverInterface,
} from "../../../../contracts/src/interfaces/IConditionResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "conditionId",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "resolve",
    outputs: [
      {
        internalType: "bool",
        name: "authorized",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IConditionResolver__factory {
  static readonly abi = _abi;
  static createInterface(): IConditionResolverInterface {
    return new Interface(_abi) as IConditionResolverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IConditionResolver {
    return new Contract(address, _abi, runner) as unknown as IConditionResolver;
  }
}
