/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace ConditionalPaymentModule {
  export type ConditionStruct = {
    conditionId: BytesLike;
    amount: BigNumberish;
    beneficiaries: AddressLike[];
    deadline: BigNumberish;
    earliestRelease: BigNumberish;
    authorized: boolean;
    released: boolean;
    releasedAmount: BigNumberish;
  };

  export type ConditionStructOutput = [
    conditionId: string,
    amount: bigint,
    beneficiaries: string[],
    deadline: bigint,
    earliestRelease: bigint,
    authorized: boolean,
    released: boolean,
    releasedAmount: bigint
  ] & {
    conditionId: string;
    amount: bigint;
    beneficiaries: string[];
    deadline: bigint;
    earliestRelease: bigint;
    authorized: boolean;
    released: boolean;
    releasedAmount: bigint;
  };
}

export interface ConditionalPaymentModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AUTHORIZE_CONDITION_TYPEHASH"
      | "DOMAIN_SEPARATOR"
      | "authorizeCondition"
      | "authorizeConditionWithSignature"
      | "core"
      | "eip712Domain"
      | "getCondition"
      | "getConditionIds"
      | "isInitialized"
      | "moduleType"
      | "onActivate"
      | "onTerminate"
      | "registerConditions"
      | "releaseCondition"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConditionAuthorized"
      | "ConditionRegistered"
      | "ConditionReleased"
      | "EIP712DomainChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AUTHORIZE_CONDITION_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeCondition",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeConditionWithSignature",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "core", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCondition",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConditionIds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "moduleType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onActivate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onTerminate",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerConditions",
    values: [
      BytesLike,
      BytesLike[],
      BigNumberish[],
      AddressLike[][],
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseCondition",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "AUTHORIZE_CONDITION_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeConditionWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "core", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConditionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "moduleType", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onActivate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onTerminate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerConditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseCondition",
    data: BytesLike
  ): Result;
}

export namespace ConditionAuthorizedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    conditionId: BytesLike,
    authorizer: AddressLike
  ];
  export type OutputTuple = [
    agreementId: string,
    conditionId: string,
    authorizer: string
  ];
  export interface OutputObject {
    agreementId: string;
    conditionId: string;
    authorizer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConditionRegisteredEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    conditionId: BytesLike,
    amount: BigNumberish,
    earliestRelease: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    conditionId: string,
    amount: bigint,
    earliestRelease: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    conditionId: string;
    amount: bigint;
    earliestRelease: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConditionReleasedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    conditionId: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    conditionId: string,
    amount: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    conditionId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConditionalPaymentModule extends BaseContract {
  connect(runner?: ContractRunner | null): ConditionalPaymentModule;
  waitForDeployment(): Promise<this>;

  interface: ConditionalPaymentModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AUTHORIZE_CONDITION_TYPEHASH: TypedContractMethod<[], [string], "view">;

  DOMAIN_SEPARATOR: TypedContractMethod<[], [string], "view">;

  authorizeCondition: TypedContractMethod<
    [agreementId: BytesLike, conditionId: BytesLike],
    [void],
    "nonpayable"
  >;

  authorizeConditionWithSignature: TypedContractMethod<
    [
      agreementId: BytesLike,
      conditionId: BytesLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  core: TypedContractMethod<[], [string], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getCondition: TypedContractMethod<
    [agreementId: BytesLike, conditionId: BytesLike],
    [ConditionalPaymentModule.ConditionStructOutput],
    "view"
  >;

  getConditionIds: TypedContractMethod<
    [agreementId: BytesLike],
    [string[]],
    "view"
  >;

  isInitialized: TypedContractMethod<
    [agreementId: BytesLike],
    [boolean],
    "view"
  >;

  moduleType: TypedContractMethod<[], [string], "view">;

  onActivate: TypedContractMethod<[arg0: BytesLike], [void], "nonpayable">;

  onTerminate: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerConditions: TypedContractMethod<
    [
      agreementId: BytesLike,
      conditionIds: BytesLike[],
      amounts: BigNumberish[],
      beneficiariesPerCondition: AddressLike[][],
      earliestReleases: BigNumberish[],
      deadlines: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  releaseCondition: TypedContractMethod<
    [agreementId: BytesLike, conditionId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AUTHORIZE_CONDITION_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DOMAIN_SEPARATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeCondition"
  ): TypedContractMethod<
    [agreementId: BytesLike, conditionId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizeConditionWithSignature"
  ): TypedContractMethod<
    [
      agreementId: BytesLike,
      conditionId: BytesLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "core"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCondition"
  ): TypedContractMethod<
    [agreementId: BytesLike, conditionId: BytesLike],
    [ConditionalPaymentModule.ConditionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConditionIds"
  ): TypedContractMethod<[agreementId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[agreementId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "moduleType"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onActivate"
  ): TypedContractMethod<[arg0: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onTerminate"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerConditions"
  ): TypedContractMethod<
    [
      agreementId: BytesLike,
      conditionIds: BytesLike[],
      amounts: BigNumberish[],
      beneficiariesPerCondition: AddressLike[][],
      earliestReleases: BigNumberish[],
      deadlines: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseCondition"
  ): TypedContractMethod<
    [agreementId: BytesLike, conditionId: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConditionAuthorized"
  ): TypedContractEvent<
    ConditionAuthorizedEvent.InputTuple,
    ConditionAuthorizedEvent.OutputTuple,
    ConditionAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "ConditionRegistered"
  ): TypedContractEvent<
    ConditionRegisteredEvent.InputTuple,
    ConditionRegisteredEvent.OutputTuple,
    ConditionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ConditionReleased"
  ): TypedContractEvent<
    ConditionReleasedEvent.InputTuple,
    ConditionReleasedEvent.OutputTuple,
    ConditionReleasedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;

  filters: {
    "ConditionAuthorized(bytes32,bytes32,address)": TypedContractEvent<
      ConditionAuthorizedEvent.InputTuple,
      ConditionAuthorizedEvent.OutputTuple,
      ConditionAuthorizedEvent.OutputObject
    >;
    ConditionAuthorized: TypedContractEvent<
      ConditionAuthorizedEvent.InputTuple,
      ConditionAuthorizedEvent.OutputTuple,
      ConditionAuthorizedEvent.OutputObject
    >;

    "ConditionRegistered(bytes32,bytes32,uint256,uint64,uint64)": TypedContractEvent<
      ConditionRegisteredEvent.InputTuple,
      ConditionRegisteredEvent.OutputTuple,
      ConditionRegisteredEvent.OutputObject
    >;
    ConditionRegistered: TypedContractEvent<
      ConditionRegisteredEvent.InputTuple,
      ConditionRegisteredEvent.OutputTuple,
      ConditionRegisteredEvent.OutputObject
    >;

    "ConditionReleased(bytes32,bytes32,uint256)": TypedContractEvent<
      ConditionReleasedEvent.InputTuple,
      ConditionReleasedEvent.OutputTuple,
      ConditionReleasedEvent.OutputObject
    >;
    ConditionReleased: TypedContractEvent<
      ConditionReleasedEvent.InputTuple,
      ConditionReleasedEvent.OutputTuple,
      ConditionReleasedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
  };
}
