/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace StreamModule {
  export type StreamStruct = {
    agreementId: BytesLike;
    sender: AddressLike;
    recipient: AddressLike;
    token: AddressLike;
    deposited: BigNumberish;
    claimed: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    cliff: BigNumberish;
    cancelled: boolean;
    cancelledAt: BigNumberish;
    initialized: boolean;
  };

  export type StreamStructOutput = [
    agreementId: string,
    sender: string,
    recipient: string,
    token: string,
    deposited: bigint,
    claimed: bigint,
    startTime: bigint,
    endTime: bigint,
    cliff: bigint,
    cancelled: boolean,
    cancelledAt: bigint,
    initialized: boolean
  ] & {
    agreementId: string;
    sender: string;
    recipient: string;
    token: string;
    deposited: bigint;
    claimed: bigint;
    startTime: bigint;
    endTime: bigint;
    cliff: bigint;
    cancelled: boolean;
    cancelledAt: bigint;
    initialized: boolean;
  };
}

export interface StreamModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accruedAmount"
      | "cancelStream"
      | "claim"
      | "claimableAmount"
      | "core"
      | "createStream"
      | "getStream"
      | "moduleType"
      | "onActivate"
      | "onTerminate"
      | "streams"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "StreamCancelled"
      | "StreamClaimed"
      | "StreamCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accruedAmount",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelStream",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "claimableAmount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "core", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createStream",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStream",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "moduleType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onActivate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onTerminate",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "streams", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "accruedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "core", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStream", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "moduleType", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onActivate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onTerminate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "streams", data: BytesLike): Result;
}

export namespace StreamCancelledEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    cancelledBy: AddressLike,
    refundedToSender: BigNumberish,
    remainingClaimable: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    cancelledBy: string,
    refundedToSender: bigint,
    remainingClaimable: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    cancelledBy: string;
    refundedToSender: bigint;
    remainingClaimable: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamClaimedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish,
    totalClaimed: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    recipient: string,
    amount: bigint,
    totalClaimed: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    recipient: string;
    amount: bigint;
    totalClaimed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCreatedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    deposited: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish,
    cliff: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    sender: string,
    recipient: string,
    deposited: bigint,
    startTime: bigint,
    endTime: bigint,
    cliff: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    sender: string;
    recipient: string;
    deposited: bigint;
    startTime: bigint;
    endTime: bigint;
    cliff: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StreamModule extends BaseContract {
  connect(runner?: ContractRunner | null): StreamModule;
  waitForDeployment(): Promise<this>;

  interface: StreamModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accruedAmount: TypedContractMethod<
    [agreementId: BytesLike, timestamp: BigNumberish],
    [bigint],
    "view"
  >;

  cancelStream: TypedContractMethod<
    [agreementId: BytesLike],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;

  claimableAmount: TypedContractMethod<
    [agreementId: BytesLike],
    [bigint],
    "view"
  >;

  core: TypedContractMethod<[], [string], "view">;

  createStream: TypedContractMethod<
    [
      agreementId: BytesLike,
      recipient: AddressLike,
      startTime: BigNumberish,
      endTime: BigNumberish,
      cliff: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getStream: TypedContractMethod<
    [agreementId: BytesLike],
    [StreamModule.StreamStructOutput],
    "view"
  >;

  moduleType: TypedContractMethod<[], [string], "view">;

  onActivate: TypedContractMethod<
    [agreementId: BytesLike],
    [void],
    "nonpayable"
  >;

  onTerminate: TypedContractMethod<
    [agreementId: BytesLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;

  streams: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean
      ] & {
        agreementId: string;
        sender: string;
        recipient: string;
        token: string;
        deposited: bigint;
        claimed: bigint;
        startTime: bigint;
        endTime: bigint;
        cliff: bigint;
        cancelled: boolean;
        cancelledAt: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accruedAmount"
  ): TypedContractMethod<
    [agreementId: BytesLike, timestamp: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelStream"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableAmount"
  ): TypedContractMethod<[agreementId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "core"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createStream"
  ): TypedContractMethod<
    [
      agreementId: BytesLike,
      recipient: AddressLike,
      startTime: BigNumberish,
      endTime: BigNumberish,
      cliff: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getStream"
  ): TypedContractMethod<
    [agreementId: BytesLike],
    [StreamModule.StreamStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "moduleType"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onActivate"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onTerminate"
  ): TypedContractMethod<
    [agreementId: BytesLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "streams"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean
      ] & {
        agreementId: string;
        sender: string;
        recipient: string;
        token: string;
        deposited: bigint;
        claimed: bigint;
        startTime: bigint;
        endTime: bigint;
        cliff: bigint;
        cancelled: boolean;
        cancelledAt: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "StreamCancelled"
  ): TypedContractEvent<
    StreamCancelledEvent.InputTuple,
    StreamCancelledEvent.OutputTuple,
    StreamCancelledEvent.OutputObject
  >;
  getEvent(
    key: "StreamClaimed"
  ): TypedContractEvent<
    StreamClaimedEvent.InputTuple,
    StreamClaimedEvent.OutputTuple,
    StreamClaimedEvent.OutputObject
  >;
  getEvent(
    key: "StreamCreated"
  ): TypedContractEvent<
    StreamCreatedEvent.InputTuple,
    StreamCreatedEvent.OutputTuple,
    StreamCreatedEvent.OutputObject
  >;

  filters: {
    "StreamCancelled(bytes32,address,uint256,uint256)": TypedContractEvent<
      StreamCancelledEvent.InputTuple,
      StreamCancelledEvent.OutputTuple,
      StreamCancelledEvent.OutputObject
    >;
    StreamCancelled: TypedContractEvent<
      StreamCancelledEvent.InputTuple,
      StreamCancelledEvent.OutputTuple,
      StreamCancelledEvent.OutputObject
    >;

    "StreamClaimed(bytes32,address,uint256,uint256)": TypedContractEvent<
      StreamClaimedEvent.InputTuple,
      StreamClaimedEvent.OutputTuple,
      StreamClaimedEvent.OutputObject
    >;
    StreamClaimed: TypedContractEvent<
      StreamClaimedEvent.InputTuple,
      StreamClaimedEvent.OutputTuple,
      StreamClaimedEvent.OutputObject
    >;

    "StreamCreated(bytes32,address,address,uint256,uint64,uint64,uint64)": TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;
    StreamCreated: TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;
  };
}
