/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AgreementCore {
  export type CreateParamsStruct = {
    agreementId: BytesLike;
    payer: AddressLike;
    token: AddressLike;
    principal: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    metadataHash: BytesLike;
    module: AddressLike;
  };

  export type CreateParamsStructOutput = [
    agreementId: string,
    payer: string,
    token: string,
    principal: bigint,
    startTime: bigint,
    endTime: bigint,
    metadataHash: string,
    module: string
  ] & {
    agreementId: string;
    payer: string;
    token: string;
    principal: bigint;
    startTime: bigint;
    endTime: bigint;
    metadataHash: string;
    module: string;
  };

  export type AgreementStruct = {
    agreementId: BytesLike;
    payer: AddressLike;
    token: AddressLike;
    principal: BigNumberish;
    deposited: BigNumberish;
    released: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    status: BigNumberish;
    metadataHash: BytesLike;
    module: AddressLike;
    createdAt: BigNumberish;
    activatedAt: BigNumberish;
  };

  export type AgreementStructOutput = [
    agreementId: string,
    payer: string,
    token: string,
    principal: bigint,
    deposited: bigint,
    released: bigint,
    startTime: bigint,
    endTime: bigint,
    status: bigint,
    metadataHash: string,
    module: string,
    createdAt: bigint,
    activatedAt: bigint
  ] & {
    agreementId: string;
    payer: string;
    token: string;
    principal: bigint;
    deposited: bigint;
    released: bigint;
    startTime: bigint;
    endTime: bigint;
    status: bigint;
    metadataHash: string;
    module: string;
    createdAt: bigint;
    activatedAt: bigint;
  };
}

export interface AgreementCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DOMAIN_SEPARATOR"
      | "activateAgreement"
      | "agreementCounter"
      | "agreements"
      | "allowedTokens"
      | "cancelAgreement"
      | "createAgreement"
      | "eip712Domain"
      | "expireAgreement"
      | "fundAgreement"
      | "getAgreement"
      | "getNonce"
      | "grantAuthorization"
      | "isAuthorized"
      | "nonces"
      | "protocolAdmin"
      | "releaseTo"
      | "remaining"
      | "revokeAuthorization"
      | "setAllowedToken"
      | "useNonce"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgreementActivated"
      | "AgreementCancelled"
      | "AgreementCreated"
      | "AgreementExpired"
      | "AgreementFunded"
      | "AgreementSettled"
      | "AuthorizationGranted"
      | "AuthorizationRevoked"
      | "EIP712DomainChanged"
      | "PaymentReleased"
      | "RefundIssued"
      | "TokenAllowed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activateAgreement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agreementCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agreements",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAgreement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [AgreementCore.CreateParamsStruct, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "expireAgreement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundAgreement",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNonce",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAuthorization",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nonces",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseTo",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "remaining",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAuthorization",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "useNonce",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agreementCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agreements", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expireAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "releaseTo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remaining", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "useNonce", data: BytesLike): Result;
}

export namespace AgreementActivatedEvent {
  export type InputTuple = [agreementId: BytesLike, activatedAt: BigNumberish];
  export type OutputTuple = [agreementId: string, activatedAt: bigint];
  export interface OutputObject {
    agreementId: string;
    activatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementCancelledEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    cancelledBy: AddressLike,
    refundedAmount: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    cancelledBy: string,
    refundedAmount: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    cancelledBy: string;
    refundedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementCreatedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    payer: AddressLike,
    token: AddressLike,
    principal: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish,
    metadataHash: BytesLike,
    module: AddressLike
  ];
  export type OutputTuple = [
    agreementId: string,
    payer: string,
    token: string,
    principal: bigint,
    startTime: bigint,
    endTime: bigint,
    metadataHash: string,
    module: string
  ];
  export interface OutputObject {
    agreementId: string;
    payer: string;
    token: string;
    principal: bigint;
    startTime: bigint;
    endTime: bigint;
    metadataHash: string;
    module: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementExpiredEvent {
  export type InputTuple = [agreementId: BytesLike];
  export type OutputTuple = [agreementId: string];
  export interface OutputObject {
    agreementId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementFundedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    funder: AddressLike,
    amount: BigNumberish,
    totalDeposited: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    funder: string,
    amount: bigint,
    totalDeposited: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    funder: string;
    amount: bigint;
    totalDeposited: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementSettledEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    totalReleased: BigNumberish
  ];
  export type OutputTuple = [agreementId: string, totalReleased: bigint];
  export interface OutputObject {
    agreementId: string;
    totalReleased: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuthorizationGrantedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    actor: AddressLike,
    grantedBy: AddressLike
  ];
  export type OutputTuple = [
    agreementId: string,
    actor: string,
    grantedBy: string
  ];
  export interface OutputObject {
    agreementId: string;
    actor: string;
    grantedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuthorizationRevokedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    actor: AddressLike,
    revokedBy: AddressLike
  ];
  export type OutputTuple = [
    agreementId: string,
    actor: string,
    revokedBy: string
  ];
  export interface OutputObject {
    agreementId: string;
    actor: string;
    revokedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    beneficiary: AddressLike,
    amount: BigNumberish,
    conditionId: BytesLike
  ];
  export type OutputTuple = [
    agreementId: string,
    beneficiary: string,
    amount: bigint,
    conditionId: string
  ];
  export interface OutputObject {
    agreementId: string;
    beneficiary: string;
    amount: bigint;
    conditionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundIssuedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenAllowedEvent {
  export type InputTuple = [token: AddressLike, allowed: boolean];
  export type OutputTuple = [token: string, allowed: boolean];
  export interface OutputObject {
    token: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgreementCore extends BaseContract {
  connect(runner?: ContractRunner | null): AgreementCore;
  waitForDeployment(): Promise<this>;

  interface: AgreementCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DOMAIN_SEPARATOR: TypedContractMethod<[], [string], "view">;

  activateAgreement: TypedContractMethod<
    [agreementId: BytesLike],
    [void],
    "nonpayable"
  >;

  agreementCounter: TypedContractMethod<[], [bigint], "view">;

  agreements: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint
      ] & {
        agreementId: string;
        payer: string;
        token: string;
        principal: bigint;
        deposited: bigint;
        released: bigint;
        startTime: bigint;
        endTime: bigint;
        status: bigint;
        metadataHash: string;
        module: string;
        createdAt: bigint;
        activatedAt: bigint;
      }
    ],
    "view"
  >;

  allowedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  cancelAgreement: TypedContractMethod<
    [agreementId: BytesLike],
    [void],
    "nonpayable"
  >;

  createAgreement: TypedContractMethod<
    [p: AgreementCore.CreateParamsStruct, initialAuthorized: AddressLike[]],
    [string],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  expireAgreement: TypedContractMethod<
    [agreementId: BytesLike],
    [void],
    "nonpayable"
  >;

  fundAgreement: TypedContractMethod<
    [agreementId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAgreement: TypedContractMethod<
    [agreementId: BytesLike],
    [AgreementCore.AgreementStructOutput],
    "view"
  >;

  getNonce: TypedContractMethod<
    [agreementId: BytesLike, actor: AddressLike],
    [bigint],
    "view"
  >;

  grantAuthorization: TypedContractMethod<
    [agreementId: BytesLike, actor: AddressLike],
    [void],
    "nonpayable"
  >;

  isAuthorized: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  nonces: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  protocolAdmin: TypedContractMethod<[], [string], "view">;

  releaseTo: TypedContractMethod<
    [
      agreementId: BytesLike,
      beneficiary: AddressLike,
      amount: BigNumberish,
      conditionId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  remaining: TypedContractMethod<[agreementId: BytesLike], [bigint], "view">;

  revokeAuthorization: TypedContractMethod<
    [agreementId: BytesLike, actor: AddressLike],
    [void],
    "nonpayable"
  >;

  setAllowedToken: TypedContractMethod<
    [token: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  useNonce: TypedContractMethod<
    [agreementId: BytesLike, actor: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DOMAIN_SEPARATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activateAgreement"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "agreementCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agreements"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint
      ] & {
        agreementId: string;
        payer: string;
        token: string;
        principal: bigint;
        deposited: bigint;
        released: bigint;
        startTime: bigint;
        endTime: bigint;
        status: bigint;
        metadataHash: string;
        module: string;
        createdAt: bigint;
        activatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "allowedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "cancelAgreement"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [p: AgreementCore.CreateParamsStruct, initialAuthorized: AddressLike[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "expireAgreement"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundAgreement"
  ): TypedContractMethod<
    [agreementId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgreement"
  ): TypedContractMethod<
    [agreementId: BytesLike],
    [AgreementCore.AgreementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNonce"
  ): TypedContractMethod<
    [agreementId: BytesLike, actor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantAuthorization"
  ): TypedContractMethod<
    [agreementId: BytesLike, actor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAuthorized"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseTo"
  ): TypedContractMethod<
    [
      agreementId: BytesLike,
      beneficiary: AddressLike,
      amount: BigNumberish,
      conditionId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remaining"
  ): TypedContractMethod<[agreementId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeAuthorization"
  ): TypedContractMethod<
    [agreementId: BytesLike, actor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAllowedToken"
  ): TypedContractMethod<
    [token: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "useNonce"
  ): TypedContractMethod<
    [agreementId: BytesLike, actor: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "AgreementActivated"
  ): TypedContractEvent<
    AgreementActivatedEvent.InputTuple,
    AgreementActivatedEvent.OutputTuple,
    AgreementActivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementCancelled"
  ): TypedContractEvent<
    AgreementCancelledEvent.InputTuple,
    AgreementCancelledEvent.OutputTuple,
    AgreementCancelledEvent.OutputObject
  >;
  getEvent(
    key: "AgreementCreated"
  ): TypedContractEvent<
    AgreementCreatedEvent.InputTuple,
    AgreementCreatedEvent.OutputTuple,
    AgreementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementExpired"
  ): TypedContractEvent<
    AgreementExpiredEvent.InputTuple,
    AgreementExpiredEvent.OutputTuple,
    AgreementExpiredEvent.OutputObject
  >;
  getEvent(
    key: "AgreementFunded"
  ): TypedContractEvent<
    AgreementFundedEvent.InputTuple,
    AgreementFundedEvent.OutputTuple,
    AgreementFundedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementSettled"
  ): TypedContractEvent<
    AgreementSettledEvent.InputTuple,
    AgreementSettledEvent.OutputTuple,
    AgreementSettledEvent.OutputObject
  >;
  getEvent(
    key: "AuthorizationGranted"
  ): TypedContractEvent<
    AuthorizationGrantedEvent.InputTuple,
    AuthorizationGrantedEvent.OutputTuple,
    AuthorizationGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AuthorizationRevoked"
  ): TypedContractEvent<
    AuthorizationRevokedEvent.InputTuple,
    AuthorizationRevokedEvent.OutputTuple,
    AuthorizationRevokedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "RefundIssued"
  ): TypedContractEvent<
    RefundIssuedEvent.InputTuple,
    RefundIssuedEvent.OutputTuple,
    RefundIssuedEvent.OutputObject
  >;
  getEvent(
    key: "TokenAllowed"
  ): TypedContractEvent<
    TokenAllowedEvent.InputTuple,
    TokenAllowedEvent.OutputTuple,
    TokenAllowedEvent.OutputObject
  >;

  filters: {
    "AgreementActivated(bytes32,uint64)": TypedContractEvent<
      AgreementActivatedEvent.InputTuple,
      AgreementActivatedEvent.OutputTuple,
      AgreementActivatedEvent.OutputObject
    >;
    AgreementActivated: TypedContractEvent<
      AgreementActivatedEvent.InputTuple,
      AgreementActivatedEvent.OutputTuple,
      AgreementActivatedEvent.OutputObject
    >;

    "AgreementCancelled(bytes32,address,uint256)": TypedContractEvent<
      AgreementCancelledEvent.InputTuple,
      AgreementCancelledEvent.OutputTuple,
      AgreementCancelledEvent.OutputObject
    >;
    AgreementCancelled: TypedContractEvent<
      AgreementCancelledEvent.InputTuple,
      AgreementCancelledEvent.OutputTuple,
      AgreementCancelledEvent.OutputObject
    >;

    "AgreementCreated(bytes32,address,address,uint256,uint64,uint64,bytes32,address)": TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;
    AgreementCreated: TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;

    "AgreementExpired(bytes32)": TypedContractEvent<
      AgreementExpiredEvent.InputTuple,
      AgreementExpiredEvent.OutputTuple,
      AgreementExpiredEvent.OutputObject
    >;
    AgreementExpired: TypedContractEvent<
      AgreementExpiredEvent.InputTuple,
      AgreementExpiredEvent.OutputTuple,
      AgreementExpiredEvent.OutputObject
    >;

    "AgreementFunded(bytes32,address,uint256,uint256)": TypedContractEvent<
      AgreementFundedEvent.InputTuple,
      AgreementFundedEvent.OutputTuple,
      AgreementFundedEvent.OutputObject
    >;
    AgreementFunded: TypedContractEvent<
      AgreementFundedEvent.InputTuple,
      AgreementFundedEvent.OutputTuple,
      AgreementFundedEvent.OutputObject
    >;

    "AgreementSettled(bytes32,uint256)": TypedContractEvent<
      AgreementSettledEvent.InputTuple,
      AgreementSettledEvent.OutputTuple,
      AgreementSettledEvent.OutputObject
    >;
    AgreementSettled: TypedContractEvent<
      AgreementSettledEvent.InputTuple,
      AgreementSettledEvent.OutputTuple,
      AgreementSettledEvent.OutputObject
    >;

    "AuthorizationGranted(bytes32,address,address)": TypedContractEvent<
      AuthorizationGrantedEvent.InputTuple,
      AuthorizationGrantedEvent.OutputTuple,
      AuthorizationGrantedEvent.OutputObject
    >;
    AuthorizationGranted: TypedContractEvent<
      AuthorizationGrantedEvent.InputTuple,
      AuthorizationGrantedEvent.OutputTuple,
      AuthorizationGrantedEvent.OutputObject
    >;

    "AuthorizationRevoked(bytes32,address,address)": TypedContractEvent<
      AuthorizationRevokedEvent.InputTuple,
      AuthorizationRevokedEvent.OutputTuple,
      AuthorizationRevokedEvent.OutputObject
    >;
    AuthorizationRevoked: TypedContractEvent<
      AuthorizationRevokedEvent.InputTuple,
      AuthorizationRevokedEvent.OutputTuple,
      AuthorizationRevokedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "PaymentReleased(bytes32,address,uint256,bytes32)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;

    "RefundIssued(bytes32,address,uint256)": TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
    RefundIssued: TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;

    "TokenAllowed(address,bool)": TypedContractEvent<
      TokenAllowedEvent.InputTuple,
      TokenAllowedEvent.OutputTuple,
      TokenAllowedEvent.OutputObject
    >;
    TokenAllowed: TypedContractEvent<
      TokenAllowedEvent.InputTuple,
      TokenAllowedEvent.OutputTuple,
      TokenAllowedEvent.OutputObject
    >;
  };
}
