/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IAgreementModuleInterface extends Interface {
  getFunction(
    nameOrSignature: "moduleType" | "onActivate" | "onTerminate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "moduleType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onActivate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onTerminate",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "moduleType", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onActivate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onTerminate",
    data: BytesLike
  ): Result;
}

export interface IAgreementModule extends BaseContract {
  connect(runner?: ContractRunner | null): IAgreementModule;
  waitForDeployment(): Promise<this>;

  interface: IAgreementModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  moduleType: TypedContractMethod<[], [string], "view">;

  onActivate: TypedContractMethod<
    [agreementId: BytesLike],
    [void],
    "nonpayable"
  >;

  onTerminate: TypedContractMethod<
    [agreementId: BytesLike, reason: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "moduleType"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onActivate"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onTerminate"
  ): TypedContractMethod<
    [agreementId: BytesLike, reason: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
