/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAgreementModule } from "./IAgreementModule";
export type { IConditionResolver } from "./IConditionResolver";
